language: node_js
node_js:
  - "6.10.2"
cache:
  directories:
  - node_modules
git:
  depth: 3
stages:
  - build
jobs:
  include:
    - stage: build
      name: "Build frontend"
      script:
        - cd frontend
        - npm install -g yarn
        - yarn
        - yarn build
    - stage: build
      name: "Build backend"
      script:
        - cd server
        - npm install -g yarn
        - yarn
        - yarn build
